<div class="mt-3 miko-tab-contain">
	<div class="miko-tab-main">
		<a class="miko-tab-item mr-1 mb-1 {{(!isset($request->tinhtrang))?'miko-tab-active':''}}" href="{{route('admin.order.show',['man'])}}"><i class="fal fa-clipboard-list mr-2"></i> {{ __('Tất cả') }} ({{(@$itemCountOrder['allFull']>0) ? @$itemCountOrder['allFull'] : 0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==1)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>1])}}"><i class="fal fa-shopping-bag mr-2"></i> {{ __('Mới đặt') }} ({{(@$itemCountOrder['allMoidat']>0)?@$itemCountOrder['allMoidat']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==2)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>2])}}"><i class="far fa-clipboard-list-check mr-2"></i> {{ __('Đã xác nhận') }} ({{(@$itemCountOrder['allDaxacnhan']>0)?@$itemCountOrder['allDaxacnhan']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==3)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>3])}}"><i class="fal fa-truck mr-2"></i> {{ __('Đang giao') }} ({{(@$itemCountOrder['allDanggiao'])?@$itemCountOrder['allDanggiao']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==6)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>6])}}"><i class="fal fa-undo mr-2"></i> {{ __('Đang chuyển hoàn') }} ({{(@$itemCountOrder['allDangchuyenhoan']>0)?@$itemCountOrder['allDangchuyenhoan']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==7)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>7])}}"><i class="fal fa-truck-couch mr-2"></i> {{ __('Đã chuyển hoàn') }} ({{(@$itemCountOrder['allDachuyenhoan']>0)?@$itemCountOrder['allDachuyenhoan']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==4)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>4])}}"><i class="fal fa-clipboard-check mr-2"></i> {{ __('Đã giao') }} ({{(@$itemCountOrder['allDagiao']>0)?@$itemCountOrder['allDagiao']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==5)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>5])}}"><i class="fal fa-calendar-times mr-2"></i> {{ __('Đã hủy') }} ({{(@$itemCountOrder['allDahuy']>0)?@$itemCountOrder['allDahuy']:0}})</a>
	</div>
</div>